### Preprocessing of data

In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv("Annotations-file.csv", sep = ';', header=None)

In [3]:
data

,0,1,2,3,4,5,6,7,8,9,...,287,288,289,290,291,292,293,294,295,296
0,# of query,1,2,3,4,5,0.0,1,2,3,...,1,2,3,4,5,6,1,0.0,1,2
1,# of task,1,1,1,1,1,2.0,2,2,2,...,2,2,2,2,2,2,1,2.0,2,2
2,id,11,11,11,11,11,11.0,11,11,11,...,44,44,44,44,44,44,45,45.0,45,45
3,LLM,2,2,2,2,2,2.0,2,2,2,...,2,2,2,2,2,2,2,2.0,2,2
4,R1_2_data,x,NaN,x,NaN,x,NaN,x,NaN,x,...,NaN,x,x,x,NaN,NaN,x,NaN,NaN,x
5,R1_2_papers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,R1_3_concise NL query,NaN,x,x,NaN,x,NaN,x,x,x,...,x,x,x,x,x,x,x,NaN,x,x
7,R1_3_keyword queries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,R1_3_phrases,x,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,P_copypaste_phrasing,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,P_abandon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,P_action,NaN,NaN,NaN,x,x,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,x,NaN,x,x
12,P_answers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,P_apology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,P_closing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,P_hold,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,P_opening,NaN,NaN,NaN,NaN,NaN,NaN,x,NaN,NaN,...,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,P_opinion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,P_question,NaN,y,w,NaN,NaN,NaN,y,y,y,...,y,y,y,y,w,w,NaN,NaN,y,y
19,P_statement,x,NaN,NaN,NaN,NaN,NaN,x,x,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x,NaN
20,P_summary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,P_thanking,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,P_appreciation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,P_offer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,LLM_abandon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,LLM_action,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,LLM_answers,NaN,n,NaN,NaN,NaN,NaN,y,y,y,...,y,y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,y
27,LLM_apology,NaN,x,NaN,x,x,NaN,NaN,x,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,LLM_appreciation,NaN,NaN,NaN,NaN,NaN,NaN,x,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x,NaN
29,LLM_closing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,LLM_hold,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,LLM_opening,NaN,NaN,NaN,NaN,NaN,NaN,x,NaN,NaN,...,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,x,NaN
32,LLM_opinion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,LLM_question,NaN,NaN,NaN,NaN,NaN,NaN,y,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,w,NaN
34,LLM_statement,x,x,x,x,x,NaN,x,x,x,...,x,x,x,x,x,x,x,NaN,x,x
35,LLM_summary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,LLM_thanking,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,LLM_offer,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,R2_1_LLM_please,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,R2_1_P_please,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.T

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,# of query,# of task,id,LLM,R1_2_data,R1_2_papers,R1_3_concise NL query,R1_3_keyword queries,R1_3_phrases,P_copypaste_phrasing,...,LLM_hold,LLM_opening,LLM_opinion,LLM_question,LLM_statement,LLM_summary,LLM_thanking,LLM_offer,R2_1_LLM_please,R2_1_P_please
1,1,1,11,2,x,NaN,NaN,NaN,x,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
2,2,1,11,2,NaN,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
3,3,1,11,2,x,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
4,4,1,11,2,NaN,NaN,NaN,NaN,x,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,x,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,6,2,44,2,NaN,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
293,1,1,45,2,x,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
294,0.0,2.0,45.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,1,2,45,2,NaN,NaN,x,NaN,NaN,NaN,...,NaN,x,NaN,w,x,NaN,NaN,NaN,NaN,NaN
296,2,2,45,2,x,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN

In [5]:
new_header = data.T.iloc[0]
data = data.T[1:]
data.columns = new_header

In [6]:
data

,# of query,# of task,id,LLM,R1_2_data,R1_2_papers,R1_3_concise NL query,R1_3_keyword queries,R1_3_phrases,P_copypaste_phrasing,...,LLM_hold,LLM_opening,LLM_opinion,LLM_question,LLM_statement,LLM_summary,LLM_thanking,LLM_offer,R2_1_LLM_please,R2_1_P_please
1,1,1,11,2,x,NaN,NaN,NaN,x,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
2,2,1,11,2,NaN,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
3,3,1,11,2,x,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
4,4,1,11,2,NaN,NaN,NaN,NaN,x,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,x,NaN,NaN
5,5,1,11,2,x,NaN,x,NaN,NaN,x,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292,6,2,44,2,NaN,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
293,1,1,45,2,x,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN
294,0.0,2.0,45.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
295,1,2,45,2,NaN,NaN,x,NaN,NaN,NaN,...,NaN,x,NaN,w,x,NaN,NaN,NaN,NaN,NaN
296,2,2,45,2,x,NaN,x,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,x,NaN,NaN,NaN,NaN,NaN

### RQ 1: What is the observable interaction behaviour between participants and the LLMs?

#### RQ 1_1: How long are interaction sessions, how does the length of prompts and response change over time?

In [7]:
# Number of conversations per task and LLM
print('Unguided & ChatGPT & ' + str(len(data.loc[(data['# of task'] == 1) & (data['LLM'] == 1)])) + ' & ' + str(round(len(data.loc[(data['# of task'] == 1) & (data['LLM'] == 1)])/16, 2)) + ' \\\\')
print('Unguided & Perplexity & ' + str(len(data.loc[(data['# of task'] == 1) & (data['LLM'] == 2)])) + ' & ' + str(round(len(data.loc[(data['# of task'] == 1) & (data['LLM'] == 2)])/16, 2)) + ' \\\\')
print('Guided & ChatGPT & ' + str(len(data.loc[(data['# of task'] == 2) & (data['LLM'] == 1)]) - 16) + ' & ' + str(round((len(data.loc[(data['# of task'] == 2) & (data['LLM'] == 1)]) - 16)/16, 2)) + ' \\\\')
print('Guided & Perplexity & ' + str(len(data.loc[(data['# of task'] == 2) & (data['LLM'] == 2)]) - 16) + ' & ' + str(round((len(data.loc[(data['# of task'] == 2) & (data['LLM'] == 2)]) - 16)/16, 2)) + ' \\\\')

Unguided & ChatGPT & 59 & 3.69 \\
Unguided & Perplexity & 68 & 4.25 \\
Guided & ChatGPT & 58 & 3.62 \\
Guided & Perplexity & 79 & 4.94 \\

#### RQ 1_2: Did participants search for data or papers?

In [8]:
# data and paper search

data_search_t1 = {}
data_search_t2 = {}
papers_search_t1 = {}
papers_search_t2 = {}

for i, r in data.iterrows():
    if r['R1_2_data'] == 'x':
        # unguided task
        if r['# of task'] == 1:
            if r['id'] in data_search_t1:
                data_search_t1[r['id']] = data_search_t1[r['id']] + 1
            else:
                data_search_t1[r['id']] = 1
        # guided task
        else:
            if r['id'] in data_search_t2:
                data_search_t2[r['id']] = data_search_t2[r['id']] + 1
            else:
                data_search_t2[r['id']] = 1
    if r['R1_2_papers'] == 'x':
        # unguided task
        if r['# of task'] == 1:
            if r['id'] in papers_search_t1:
                papers_search_t1[r['id']] = papers_search_t1[r['id']] + 1
            else:
                papers_search_t1[r['id']] = 1
        # guided task
        else:
            if r['id'] in papers_search_t2:
                papers_search_t2[r['id']] = papers_search_t2[r['id']] + 1
            else:
                papers_search_t2[r['id']] = 1

In [9]:
# persons searching for data in unguided task
print(len(data_search_t1))
# persons searching for data in guided task
print(len(data_search_t2))
# persons searching for papers in unguided task
print(len(papers_search_t1))
# persons searching for papers in guided task
print(len(papers_search_t2))

print('___')
# persons searching for data in both task
print(len(data_search_t1.keys() & data_search_t2.keys()))
# persons searching for papers in both task
print(len(papers_search_t1.keys() & papers_search_t2.keys()))

print('___')
# persons searching for data in and papers in unguided task
print(len(data_search_t1.keys() & papers_search_t1.keys()))
# persons searching for data in and papers in unguided task
print(len(data_search_t2.keys() & papers_search_t2.keys()))

29
29
3
8
___
27
1
___
2
6

#### RQ 1_3: How did the participants formulate their prompts on a continuum from keyword queries to phrases or a concise natural language query?

In [10]:
# RQ1_3
# keyword queries to concise queries

# over both tasks
# key, no phrases, no nl
print(len(data.loc[(data['R1_3_phrases'] != 'x') & (data['R1_3_keyword queries'] == 'x') & (data['R1_3_concise NL query'] != 'x')]))
# key + phrases, no nl
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_keyword queries'] == 'x') & (data['R1_3_concise NL query'] != 'x')]))
# phrases, no nl, no key
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_concise NL query'] != 'x') & (data['R1_3_keyword queries'] != 'x')]))
# phrases + nl, no key
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_concise NL query'] == 'x') & (data['R1_3_keyword queries'] != 'x')]))
# no phrases, nl, no key
print(len(data.loc[(data['R1_3_phrases'] != 'x') & (data['R1_3_concise NL query'] == 'x') & (data['R1_3_keyword queries'] != 'x')]))

print('____')

# task 1
# key, no phrases, no nl
print(len(data.loc[(data['R1_3_phrases'] != 'x') & (data['R1_3_keyword queries'] == 'x') & (data['R1_3_concise NL query'] != 'x') & (data['# of task'] == 1)]))
# key + phrases, no nl
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_keyword queries'] == 'x') & (data['R1_3_concise NL query'] != 'x') & (data['# of task'] == 1)]))
# phrases, no nl, no key
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_concise NL query'] != 'x') & (data['R1_3_keyword queries'] != 'x') & (data['# of task'] == 1)]))
# phrases + nl, no key
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_concise NL query'] == 'x') & (data['R1_3_keyword queries'] != 'x') & (data['# of task'] == 1)]))
# no phrases, nl, no key
print(len(data.loc[(data['R1_3_phrases'] != 'x') & (data['R1_3_concise NL query'] == 'x') & (data['R1_3_keyword queries'] != 'x') & (data['# of task'] == 1)]))


print('____')
# task 2
# key, no phrases, no nl
print(len(data.loc[(data['R1_3_phrases'] != 'x') & (data['R1_3_keyword queries'] == 'x') & (data['R1_3_concise NL query'] != 'x') & (data['# of task'] != 1)]))
# key + phrases, no nl
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_keyword queries'] == 'x') & (data['R1_3_concise NL query'] != 'x') & (data['# of task'] != 1)]))
# phrases, no nl, no key
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_concise NL query'] != 'x') & (data['R1_3_keyword queries'] != 'x') & (data['# of task'] != 1)]))
# phrases + nl, no key
print(len(data.loc[(data['R1_3_phrases'] == 'x') & (data['R1_3_concise NL query'] == 'x') & (data['R1_3_keyword queries'] != 'x') & (data['# of task'] != 1)]))
# no phrases, nl, no key
print(len(data.loc[(data['R1_3_phrases'] != 'x') & (data['R1_3_concise NL query'] == 'x') & (data['R1_3_keyword queries'] != 'x') & (data['# of task'] != 1)]))

print('____')
# number of prompt instructions
print(len(data.loc[(data['R1_3_phrases'] != 'x') & (data['R1_3_concise NL query'] != 'x') & (data['R1_3_keyword queries'] != 'x')]))

3
1
5
4
251
____
2
1
3
2
119
____
1
0
2
2
132
____
32

### RQ 2: Do the interactions between participants and LLMs show characteristics associated with humanisation?

#### RQ 2_1: Do participants' and LLMs' utilised dialogue acts differ in their interactions?

In [11]:
len_chatgpt_unguided = len(data.loc[(data['# of task'] == 1) & (data['LLM'] == 1)])
len_chatgpt_guided = len(data.loc[(data['# of task'] == 2) & (data['LLM'] == 1)]) - 16
len_perplexity_unguided = len(data.loc[(data['# of task'] == 1) & (data['LLM'] == 2)])
len_perplexity_guided = len(data.loc[(data['# of task'] == 2) & (data['LLM'] == 2)]) - 16

In [12]:
fields = ['P_statement', 'LLM_statement', 'P_opinion', 'LLM_opinion', 'P_question', 'LLM_question',  'P_answers', 'LLM_answers', 'P_appreciation', 'LLM_appreciation', 'P_apology', 'LLM_apology', 'P_thanking', 'LLM_thanking',   'P_action', 'LLM_action', 'P_offer', 'LLM_offer', 'P_opening', 'LLM_opening', 'P_closing', 'LLM_closing', 'P_hold', 'LLM_hold',  'P_copypaste_phrasing', 'P_abandon']

task_1 = data.loc[data['# of task'] == 1]
task_2 = data.loc[data['# of task'] == 2]

for f in fields:
    # ChatGPT
    ds_t1_c = {}
    ds_t2_c = {}
    
    for i, r in task_1.iterrows():
        if r['LLM'] == 1 and (r[f] == 'x' or r[f] == 'y' or r[f] == 'n' or r[f] == 'my' or r[f] == 'w'):
            if r['id'] in ds_t1_c:
                ds_t1_c[r['id']] = ds_t1_c[r['id']] + 1
            else:
                ds_t1_c[r['id']] = 1
    for i, r in task_2.iterrows():
        if r['LLM'] == 1 and (r[f] == 'x' or r[f] == 'y' or r[f] == 'n' or r[f] == 'my' or r[f] == 'w'):
            if r['id'] in ds_t2_c:
                ds_t2_c[r['id']] = ds_t2_c[r['id']] + 1
            else:
                ds_t2_c[r['id']] = 1
    
    if f[0] == 'P':
        print(f[2].upper() + f[3:] + ' & ')

    # Perplexity
    ds_t1_p = {}
    ds_t2_p = {}
    
    for i, r in task_1.iterrows():
        if r['LLM'] == 2 and (r[f] == 'x' or r[f] == 'y' or r[f] == 'n' or r[f] == 'my' or r[f] == 'w'):
            if r['id'] in ds_t1_p:
                ds_t1_p[r['id']] = ds_t1_p[r['id']] + 1
            else:
                ds_t1_p[r['id']] = 1
    for i, r in task_2.iterrows():
        if r['LLM'] == 2 and (r[f] == 'x' or r[f] == 'y' or r[f] == 'n' or r[f] == 'my' or r[f] == 'w'):
            if r['id'] in ds_t2_p:
                ds_t2_p[r['id']] = ds_t2_p[r['id']] + 1
            else:
                ds_t2_p[r['id']] = 1

    # combination of LLMs
    print(  str(len(ds_t1_c) + len(ds_t1_p))                 + ' (' + str(round(data.loc[(data['# of task'] == 1)][f].count()/(len_chatgpt_unguided + len_perplexity_unguided) * 100, 2)) + '\%) & ' +\
            str(len(ds_t2_c) + len(ds_t2_p))                 + ' (' + str(round(data.loc[(data['# of task'] == 2)][f].count()/(len_chatgpt_guided + len_perplexity_guided) * 100, 2)) + '\%)')

    if f[0] == 'P':
        print(' & ')
    else:
        print('\\\\')

Statement &
20 (32.28\%) & 29 (37.96\%)
 &
32 (99.21\%) & 32 (97.81\%)
\\
Opinion &
1 (0.79\%) & 5 (3.65\%)
 &
1 (0.79\%) & 3 (3.65\%)
\\
Question &
28 (55.91\%) & 32 (76.64\%)
 &
12 (29.13\%) & 17 (34.31\%)
\\
Answers &
3 (3.94\%) & 5 (5.84\%)
 &
16 (22.83\%) & 23 (28.47\%)
\\
Appreciation &
0 (0.0\%) & 2 (1.46\%)
 &
1 (0.79\%) & 13 (12.41\%)
\\
Apology &
0 (0.0\%) & 1 (0.73\%)
 &
2 (3.15\%) & 5 (3.65\%)
\\
Thanking &
2 (1.57\%) & 10 (8.76\%)
 &
1 (0.79\%) & 1 (0.73\%)
\\
Action &
26 (49.61\%) & 22 (27.01\%)
 &
0 (0.0\%) & 0 (0.0\%)
\\
Offer &
0 (0.0\%) & 0 (0.0\%)
 &
17 (40.94\%) & 25 (55.47\%)
\\
Opening &
2 (2.36\%) & 21 (16.06\%)
 &
0 (0.0\%) & 22 (18.98\%)
\\
Closing &
0 (0.0\%) & 2 (1.46\%)
 &
0 (0.0\%) & 1 (0.73\%)
\\
Hold &
0 (0.0\%) & 0 (0.0\%)
 &
1 (0.79\%) & 4 (2.92\%)
\\
Copypaste_phrasing &
5 (7.09\%) & 4 (3.65\%)
 &
Abandon &
3 (2.36\%) & 1 (0.73\%)
 &

In [13]:
# more in depth, not depicted in paper but some numbers were used
fields = ['P_statement', 'LLM_statement', 'P_opinion', 'LLM_opinion', 'P_question', 'LLM_question',  'P_answers', 'LLM_answers', 'P_appreciation', 'LLM_appreciation', 'P_apology', 'LLM_apology', 'P_thanking', 'LLM_thanking',   'P_action', 'LLM_action', 'P_offer', 'LLM_offer', 'P_opening', 'LLM_opening', 'P_closing', 'LLM_closing', 'P_hold', 'LLM_hold',  'P_copypaste_phrasing', 'P_abandon']

task_1 = data.loc[data['# of task'] == 1]
task_2 = data.loc[data['# of task'] == 2]

for f in fields:
    # ChatGPT
    ds_t1_c = {}
    ds_t2_c = {}
    
    for i, r in task_1.iterrows():
        if r['LLM'] == 1 and (r[f] == 'x' or r[f] == 'y' or r[f] == 'n' or r[f] == 'my' or r[f] == 'w'):
            if r['id'] in ds_t1_c:
                ds_t1_c[r['id']] = ds_t1_c[r['id']] + 1
            else:
                ds_t1_c[r['id']] = 1
    for i, r in task_2.iterrows():
        if r['LLM'] == 1 and (r[f] == 'x' or r[f] == 'y' or r[f] == 'n' or r[f] == 'my' or r[f] == 'w'):
            if r['id'] in ds_t2_c:
                ds_t2_c[r['id']] = ds_t2_c[r['id']] + 1
            else:
                ds_t2_c[r['id']] = 1
    
    if f[0] == 'P':
        print(f[2].upper() + f[3:] + ' & ')

    print(  str(len(ds_t1_c))                 + ' (' + str(round(data.loc[(data['# of task'] == 1) & (data['LLM'] == 1)][f].count()/len_chatgpt_unguided * 100, 2)) + ') & ' +\
            str(len(ds_t2_c))                 + ' (' + str(round(data.loc[(data['# of task'] == 2) & (data['LLM'] == 1)][f].count()/len_chatgpt_guided * 100, 2)) + ') & ')

    # Perplexity
    ds_t1_p = {}
    ds_t2_p = {}
    
    for i, r in task_1.iterrows():
        if r['LLM'] == 2 and (r[f] == 'x' or r[f] == 'y' or r[f] == 'n' or r[f] == 'my' or r[f] == 'w'):
            if r['id'] in ds_t1_p:
                ds_t1_p[r['id']] = ds_t1_p[r['id']] + 1
            else:
                ds_t1_p[r['id']] = 1
    for i, r in task_2.iterrows():
        if r['LLM'] == 2 and (r[f] == 'x' or r[f] == 'y' or r[f] == 'n' or r[f] == 'my' or r[f] == 'w'):
            if r['id'] in ds_t2_p:
                ds_t2_p[r['id']] = ds_t2_p[r['id']] + 1
            else:
                ds_t2_p[r['id']] = 1
    
    print(  str(len(ds_t1_p))                 + ' (' + str(round(data.loc[(data['# of task'] == 1) & (data['LLM'] == 2)][f].count()/len_perplexity_unguided * 100, 2)) + ') & ' +\
            str(len(ds_t2_p))                 + ' (' + str(round(data.loc[(data['# of task'] == 2) & (data['LLM'] == 2)][f].count()/len_perplexity_guided * 100, 2)) + ') & ')


    # combination of LLMs
    print(  str(len(ds_t1_c) + len(ds_t1_p))                 + ' (' + str(round(data.loc[(data['# of task'] == 1)][f].count()/(len_chatgpt_unguided + len_perplexity_unguided) * 100, 2)) + ') & ' +\
            str(len(ds_t2_c) + len(ds_t2_p))                 + ' (' + str(round(data.loc[(data['# of task'] == 2)][f].count()/(len_chatgpt_guided + len_perplexity_guided) * 100, 2)) + ')')

    if f[0] == 'P':
        print(' & ')
    else:
        print('\\\\')

Statement &
11 (37.29) & 15 (43.1) &
9 (27.94) & 14 (34.18) &
20 (32.28) & 29 (37.96)
 &
16 (100.0) & 16 (98.28) &
16 (98.53) & 16 (97.47) &
32 (99.21) & 32 (97.81)
\\
Opinion &
0 (0.0) & 4 (6.9) &
1 (1.47) & 1 (1.27) &
1 (0.79) & 5 (3.65)
 &
1 (1.69) & 2 (6.9) &
0 (0.0) & 1 (1.27) &
1 (0.79) & 3 (3.65)
\\
Question &
14 (52.54) & 16 (70.69) &
14 (58.82) & 16 (81.01) &
28 (55.91) & 32 (76.64)
 &
11 (61.02) & 13 (68.97) &
1 (1.47) & 4 (8.86) &
12 (29.13) & 17 (34.31)
\\
Answers &
1 (5.08) & 5 (12.07) &
2 (2.94) & 0 (1.27) &
3 (3.94) & 5 (5.84)
 &
5 (22.03) & 10 (24.14) &
11 (23.53) & 13 (31.65) &
16 (22.83) & 23 (28.47)
\\
Appreciation &
0 (0.0) & 2 (3.45) &
0 (0.0) & 0 (0.0) &
0 (0.0) & 2 (1.46)
 &
1 (1.69) & 5 (13.79) &
0 (0.0) & 8 (11.39) &
1 (0.79) & 13 (12.41)
\\
Apology &
0 (0.0) & 1 (1.72) &
0 (0.0) & 0 (0.0) &
0 (0.0) & 1 (0.73)
 &
0 (0.0) & 0 (0.0) &
2 (5.88) & 5 (6.33) &
2 (3.15) & 5 (3.65)
\\
Thanking &
2 (3.39) & 6 (10.34) &
0 (0.0) & 4 (7.59) &
2 (1.57) & 10 (8.76)
 &
1 (1.69) & 0 (0.0) &
0 (0.0) & 1 (1.27) &
1 (0.79) & 1 (0.73)
\\
Action &
13 (45.76) & 12 (34.48) &
13 (52.94) & 10 (21.52) &
26 (49.61) & 22 (27.01)
 &
0 (0.0) & 0 (0.0) &
0 (0.0) & 0 (0.0) &
0 (0.0) & 0 (0.0)
\\
Offer &
0 (0.0) & 0 (0.0) &
0 (0.0) & 0 (0.0) &
0 (0.0) & 0 (0.0)
 &
15 (84.75) & 16 (100.0) &
2 (2.94) & 9 (22.78) &
17 (40.94) & 25 (55.47)
\\
Opening &
2 (5.08) & 9 (15.52) &
0 (0.0) & 12 (16.46) &
2 (2.36) & 21 (16.06)
 &
0 (0.0) & 8 (17.24) &
0 (0.0) & 14 (20.25) &
0 (0.0) & 22 (18.98)
\\
Closing &
0 (0.0) & 1 (1.72) &
0 (0.0) & 1 (1.27) &
0 (0.0) & 2 (1.46)
 &
0 (0.0) & 1 (1.72) &
0 (0.0) & 0 (0.0) &
0 (0.0) & 1 (0.73)
\\
Hold &
0 (0.0) & 0 (0.0) &
0 (0.0) & 0 (0.0) &
0 (0.0) & 0 (0.0)
 &
1 (1.69) & 4 (6.9) &
0 (0.0) & 0 (0.0) &
1 (0.79) & 4 (2.92)
\\
Copypaste_phrasing &
1 (3.39) & 2 (3.45) &
4 (10.29) & 2 (3.8) &
5 (7.09) & 4 (3.65)
 &
Abandon &
2 (3.39) & 0 (0.0) &
1 (1.47) & 1 (1.27) &
3 (2.36) & 1 (0.73)
 &

In [14]:
# How many yes/no and wh-questions were posed by participants and LLMs, how many yes/no questions were answered
LLM_query_yn = 0
LLM_query_w = 0

part_query_yn = 0
part_query_w = 0

LLM_answer_yn = 0
part_answer_yn = 0

for i, r in data.iterrows():
    if r['P_question'] == 'y' or r['P_question'] == 'my':
        part_query_yn += 1
        
        if r['LLM_answers'] == 'y' or r['LLM_answers'] == 'n':
            LLM_answer_yn += 1

    if r['P_question'] == 'w':
        part_query_w += 1

    if r['LLM_question'] == 'y' or r['LLM_question'] == 'my':
        LLM_query_yn += 1
        
    if r['P_answers'] == 'y' or r['P_answers'] == 'n':
        part_answer_yn += 1

    if r['LLM_question'] == 'w':
        LLM_query_w += 1
        
print('participants, yes/no questions: ' + str(part_query_yn))
print('participants, wh questions: ' + str(part_query_w))

print('participants, yes/no answers: ' + str(part_answer_yn))

print('___')
print('LLMs, yes/no questions: ' + str(LLM_query_yn))
print('LLMs, wh questions: ' + str(LLM_query_w))

print('LLMs, yes/no questions: ' + str(LLM_answer_yn))

participants, yes/no questions: 108
participants, wh questions: 68
participants, yes/no answers: 11
___
LLMs, yes/no questions: 77
LLMs, wh questions: 7
LLMs, yes/no questions: 65